version: "3.2"
services:
  php:
    image: php:7.2.7-fpm-alpine3.7
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: php
  apache:
    build:
      context: './conf/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "8181:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: apache
networks:
  frontend:
  backend:
volumes:
    data:
