version: '3'

services:
  apacheweb:
    build: ./conf
    ports:
      - '8181:80'
    volumes:
      - ./web:/var/www/html
      - ./conf/sri.asir4all.ss.conf:/etc/apache2/sites-available/000-default.conf
      - ./conf/claves.digest:/etc/apache2/claves.digest
      - ./conf/claves.basic:/etc/apache2/claves.basic
